# Turn VM back on
steps:
  - name: europe-west1-docker.pkg.dev/tor-p-a-nils-snd-soda/cointainer/google-cloud-gcp-tools-container:latest
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "» VARIABLES"
        echo 'Instance ID : ${_INSTANCE_ID}'
        echo 'Zone        : ${_ZONE}'
        echo 'Project ID  : ${_PROJECT_ID}'
        echo 'JSON Body   : ${_JSON_BODY}'
        echo
        cd "/workspace/cloudbuild/" || exit 9
        bash on-again.sh "${_INSTANCE_ID}" "${_ZONE}" "${_PROJECT_ID}" || exit 9
tags: ["on-again-gce-vm"]
timeout: 600s