name: "CI"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    # The type of runner that the job will run on
    # https://github.com/actions/virtual-environments/
    # [x] shellcheck
    # [x] terraform
    # [x] ansible
    # [ ] ansible-lint
    # [_] flake8
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install ansible-lint flake8
      - name: Checkout
        uses: actions/checkout@v4
      # https://github.com/marketplace/actions/setup-tflint
      - name: Install tflint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: latest
      - name: Test
        run: cd t && bash test.sh