name: "CI"

on:
  push:
    branches: [master, slalom]
  pull_request:
    branches: [master, slalom]
  workflow_dispatch:

jobs:
  test:
    # The type of runner that the job will run on
    # https://github.com/actions/virtual-environments/
    #
    # Ubuntu 24.04:
    #  [x] shellcheck
    #  [_] terraform
    #  [x] ansible
    #  [ ] ansible-lint
    #  [_] flake8
    #  [x] yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo pip install flake8
          sudo pip install ansible-lint
      # https://github.com/hashicorp/setup-terraform
      - uses: hashicorp/setup-terraform@v3

      # https://github.com/marketplace/actions/setup-tflint
      - name: Install tflint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
      - name: Test
        run: cd test && bash test.sh