name: "CI"

on:
  push:
    branches: [master, slalom]
  pull_request:
    branches: [master, slalom]
  workflow_dispatch:

jobs:
  test:
    # The type of runner that the job will run on
    # https://github.com/actions/virtual-environments/
    #
    # Ubuntu 24.04:
    #  [x] shellcheck
    #  [_] terraform
    #  [x] ansible
    #  [ ] ansible-lint
    #  [_] flake8
    #  [x] yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r test/requirements.txt
      # https://github.com/hashicorp/setup-terraform
      - uses: hashicorp/setup-terraform@v3

      # https://github.com/marketplace/actions/setup-tflint
      - name: Install tflint
        uses: terraform-linters/setup-tflint@v5
        with:
          tflint_version: latest
      - name: Test
        run: |
          source .venv/bin/activate
          cd test && bash test.sh
